### ISSUE TITLE
make_psfmasks.py issue on windows

### ISSUE THREAD

**Issue by b-michelson** [kammerje/spaceKLIP#154]
`Traceback (most recent call last):

  File "C:\Users\becca\spaceKLIP\spaceKLIP\make_psfmasks.py", line 123, in <module>
    hdul.writeto('resources/transmissions/' + fitsfile, output_verify='fix', overwrite=True)

  File "C:\Users\becca\anaconda3\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 1010, in writeto
    fileobj = _File(fileobj, mode=mode, overwrite=overwrite)

  File "C:\Users\becca\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 217, in __init__
    self._open_filename(fileobj, mode, overwrite)

  File "C:\Users\becca\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 615, in _open_filename
    self._overwrite_existing(overwrite, None, True)

  File "C:\Users\becca\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 496, in _overwrite_existing
    os.remove(self.name)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'resources/transmissions/JWST_MIRI_F1065C_transmission_webbpsf-ext_v2.fits'`

**Comment by AarynnCarter** [comment]
Hi Becca, what was the outcome of you trying to get spaceKLIP working on a Windows machine? I remember that we realised that the jwst pipeline does not support Windows, so curious what your next steps were / are. Thanks!

**Comment by b-michelson** [comment]
Hi Aarynn,

In all honesty, I've been using our lab computer here at Smith for
spaceKLIP and haven't pursued running it on my Windows machine yet. I'm
considering running a virtual Mac machine on my laptop but have yet to do
some research on how to do that!

Becca

**Comment by AarynnCarter** [comment]
Okay no worries, in that case I will close this, and assume that spaceKLIP similarly does not support Windows at this time. Thanks :)
